package com.adi;

/**
 * @author zhoukewen
 * @since 2019-09-05
 */
public interface Constant {

    // ------------------- JVMTI EVENT --------------------

    int JVMTI_MIN_EVENT_TYPE_VAL = 50;
    int JVMTI_EVENT_VM_INIT = 50;
    int JVMTI_EVENT_VM_DEATH = 51;
    int JVMTI_EVENT_THREAD_START = 52;
    int JVMTI_EVENT_THREAD_END = 53;
    int JVMTI_EVENT_CLASS_FILE_LOAD_HOOK = 54;
    int JVMTI_EVENT_CLASS_LOAD = 55;
    int JVMTI_EVENT_CLASS_PREPARE = 56;
    int JVMTI_EVENT_VM_START = 57;
    int JVMTI_EVENT_EXCEPTION = 58;
    int JVMTI_EVENT_EXCEPTION_CATCH = 59;
    int JVMTI_EVENT_SINGLE_STEP = 60;
    int JVMTI_EVENT_FRAME_POP = 61;
    int JVMTI_EVENT_BREAKPOINT = 62;
    int JVMTI_EVENT_FIELD_ACCESS = 63;
    int JVMTI_EVENT_FIELD_MODIFICATION = 64;
    int JVMTI_EVENT_METHOD_ENTRY = 65;
    int JVMTI_EVENT_METHOD_EXIT = 66;
    int JVMTI_EVENT_NATIVE_METHOD_BIND = 67;
    int JVMTI_EVENT_COMPILED_METHOD_LOAD = 68;
    int JVMTI_EVENT_COMPILED_METHOD_UNLOAD = 69;
    int JVMTI_EVENT_DYNAMIC_CODE_GENERATED = 70;
    int JVMTI_EVENT_DATA_DUMP_REQUEST = 71;
    int JVMTI_EVENT_MONITOR_WAIT = 73;
    int JVMTI_EVENT_MONITOR_WAITED = 74;
    int JVMTI_EVENT_MONITOR_CONTENDED_ENTER = 75;
    int JVMTI_EVENT_MONITOR_CONTENDED_ENTERED = 76;
    int JVMTI_EVENT_RESOURCE_EXHAUSTED = 80;
    int JVMTI_EVENT_GARBAGE_COLLECTION_START = 81;
    int JVMTI_EVENT_GARBAGE_COLLECTION_FINISH = 82;
    int JVMTI_EVENT_OBJECT_FREE = 83;
    int JVMTI_EVENT_VM_OBJECT_ALLOC = 84;
    int JVMTI_MAX_EVENT_TYPE_VAL = 84;

    // ------------------- JVMTI EVENT End--------------------
}
